### ISSUE TITLE
Feature: send to MQTT 

### ISSUE THREAD

**Issue by ntableman** [beele/homebridge-unifi-protect-camera-motion#74] opened 2020-08-26 11:14 UTC
An awesome feature would be to send to a MQTT topic when there is an event and even better would be what the enhanced detection thinks is there. Then I could do all kinds of actions and such off of this message.

**Comment by beele** [comment] 2020-08-28 15:35
Closing this since it is a duplicate of #21

**Closed by beele** 2020-08-28 15:35 UTC
