### ISSUE TITLE
No streaming

### ISSUE THREAD

**Issue by loop2** [beele/homebridge-unifi-protect-camera-motion#4] opened 2019-10-29 14:26 UTC
HI, great implementation but i can't see the streaming RTSP.
I have set the port of RTSP 7447 and reduce the max resolution to 640x360 but i only see the updated snapshot but not the streaming...
homebridge is installed on macOS, any idea?
thanks

**Comment by technstuff** [comment] 2019-11-08 04:59
Same Issue hear

[Unifi protect cameras & motion sensors] Start streaming video from Front yard with 640x360@132kBit
[11/7/2019, 8:55:54 PM] [Unifi protect cameras & motion sensors] Start streaming video from Front yard with 640x360@132kBit
[11/7/2019, 8:55:58 PM] [Unifi protect cameras & motion sensors] ERROR: FFmpeg exited with code 1
[11/7/2019, 8:55:58 PM] [Unifi protect cameras & motion sensors] ERROR: FFmpeg exited with code 1

**Comment by beele** [comment] 2019-11-18 09:01
Make sure that the RTSP stream is working, test it with VLC or quicktime player. If that works make sure FFmpeg is working correctly.

Try setting the stream quality exactly as shown in the image in the readme.

**Comment by technstuff** [comment] 2019-11-18 09:05
using Homebridge Camera Ffmpeg with no issues. So the rtsp and ffmpg is working

**Comment by beele** [comment] 2019-11-18 09:13
To debug a little:

- Go to where the plugin installed and open the index.js file with a command line editor (vim/nano/...)
- Under line 73 add "self.log(videoConfigCopy.source);" without the quotes.
- Save the file and restart homebridge
- If this prints the correct stream URL we can rule that out as the culprit.

- Go into the ffmpeg folder under src and open ffmpeg.js
- Save the file and restart homebridge
- On line 30 change the line: "this.debug = ffmpegOpt.debug;" to "this.debug = true"
- Paste the (redacted) detailed logging of the ffmpeg error here.

**Comment by beele** [comment] 2019-12-02 07:52
@loop2 @technstuff have you tested this with the additions I said for debugging? Otherwise I'm going to close this issue.

**Comment by tslamparter** [comment] 2019-12-06 02:28
@beele I'm having this issue now that I fixed the other issue. I modified the files as you suggested and get this at the end:
`Successfully opened the file.
Parsing a group of options: output url -.
Applying option map (set input stream mapping) with argument 0:1.
Applying option vcodec (force video codec ('copy' to copy stream)) with argument h264.
Successfully parsed a group of options.
Opening an output file: -.
[NULL @ 0x1d95a50] Unable to find a suitable output format for 'pipe:'
pipe:: Invalid argument`

**Comment by beele** [comment] 2019-12-16 08:25
For more information, what camera's do you have? @tslamparter

**Comment by tslamparter** [comment] 2019-12-16 16:09
@beele it turns out I'm a dingus. When I copied and pasted your config example, I forgot to edit the "vcodec" to h264 OR h264_omx. It works now. I'm not sure if this is the same problem the other users were having, but it gave me the same error as them. Thanks for all the help and I'm loving this version unifi homebridge. Also I have regular G3s.

**Comment by beele** [comment] 2020-01-08 06:24
@technstuff @loop2 Have you guys been able to get this fixed?
If not check your config to make sure the config is adjusted so "vcodec" is set to h264 OR h264_omx

**Closed** 2020-01-24 12:35 UTC

**Comment by mahuch** [comment] 2020-01-31 12:51
Same problem here. Homebridge is installed on macOS.
I think the problem is FFmpeg on OS X. 

How do I install it correctly?
