### ISSUE TITLE
ERROR: FFmpeg exited with code 1

### ISSUE THREAD

**Issue by VentingBow5** [beele/homebridge-unifi-protect-camera-motion#44] opened 2020-05-24 11:07 UTC
Hi beele,

I do have the same problem with a UVC G3 Pro as @mrhsiao.

[5/24/2020, 13:03:20] [Unifi Protect] Start streaming video from Achterdeur with 640:360@15fps (132kBit)
[5/24/2020, 13:03:28] [Unifi Protect] ERROR: FFmpeg exited with code 1

It is a fresh install with one other plugin installed: Ring.

Cheers.

**Comment by tslamparter** [comment] 2020-05-25 00:01
I'm having the same issue. Fresh install on my new RPi 4, 4gig. I used the official homebridge image. Here is what I have from my logs. (Node.js Version = v12.16.3, Npm Version = v6.14.5)


**ffmpeg version:**
ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal
libavutil      56. 40.100 / 56. 40.100
libavcodec     58. 68.102 / 58. 68.102
libavformat    58. 38.100 / 58. 38.100
libavdevice    58.  9.103 / 58.  9.103
libavfilter     7. 75.100 /  7. 75.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100




**Log**
`[h264 @ 0x2aeada0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3

[graph 1 input from stream 0:1 @ 0x2b1a8f0] Setting 'video_size' to value '1024x576'
[graph 1 input from stream 0:1 @ 0x2b1a8f0] Setting 'pix_fmt' to value '12'

[graph 1 input from stream 0:1 @ 0x2b1a8f0] Setting 'time_base' to value '1/90000'
[graph 1 input from stream 0:1 @ 0x2b1a8f0] Setting 'pixel_aspect' to value '189/190'
[graph 1 input from stream 0:1 @ 0x2b1a8f0] Setting 'frame_rate' to value '15/1'
[graph 1 input from stream 0:1 @ 0x2b1a8f0] w:1024 h:576 pixfmt:yuvj420p tb:1/90000 fr:15/1 sar:189/190
[format @ 0x2b39590] Setting 'pix_fmts' to value 'yuv420p'

[auto_scaler_0 @ 0x2ae0970] Setting 'flags' to value 'bicubic'

[auto_scaler_0 @ 0x2ae0970] w:iw h:ih flags:'bicubic' interl:0
[format @ 0x2b39590] auto-inserting filter 'auto_scaler_0' between the filter 'Parsed_null_0' and the filter 'format'

[AVFilterGraph @ 0x2cfb700] query_formats: 4 queried, 2 merged, 1 already done, 0 delayed

[swscaler @ 0x2dbf7b0] deprecated pixel format used, make sure you did set range correctly

[auto_scaler_0 @ 0x2ae0970] w:1024 h:576 fmt:yuvj420p sar:189/190 -> w:1024 h:576 fmt:yuv420p sar:189/190 flags:0x4

[mpeg4 @ 0x2af1360] Either both buffer size and max rate or neither must be specified

Error initializing output stream 1:0 -- Error while opening encoder for output stream #1:0 - maybe incorrect parameters such as bit_rate, rate, width or height

[AVIOContext @ 0x2ca9b50] Statistics: 0 seeks, 6 writeouts

[AVIOContext @ 0x2b170d0] Statistics: 0 seeks, 0 writeouts

Conversion failed!

[5/24/2020, 11:39:25] [Unifi protect cameras & motion sensors] ERROR: FFmpeg exited with code 1`

**Comment by ciscosurplus** [comment] 2020-05-25 13:24
I was having the same issue until I increased max width, max height and max bitrate. 

1024 and 576 seem to request a lower def stream

**Comment by beele** [comment] 2020-05-25 17:21
@VentingBow5 @tslamparter If you install the homebridge-camera-ffmpeg plugin and put the camera rtsp url in there, does the video work then, if so the problem is not with ffmpeg and we need to look further.

**Comment by a-rodriguez** [comment] 2020-05-25 19:36
I am having the same issue. @beele I tried what you suggested above with homebridge-camera-ffmpeg and I am getting the same error.

`[5/25/2020, 15:34:05] [Camera-ffmpeg] Start streaming video from Front Door Test with 1280:720@10fps (299kBit)
[5/25/2020, 15:34:05] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1`

Let me know if I can provide more details.

**Comment by tslamparter** [comment] 2020-05-25 20:28
@beele I tried your suggestion and still get an exited code 1 from the homebridge-camera-ffmpeg plugin. I played around with the max height, width, and bitrate and couldn't get any combination to work.

**Comment by ciscosurplus** [comment] 2020-05-25 20:35
My working config I also updated to the latest ffmpeg homebrigde 


  "videoConfig": {
                "maxStreams": 2,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 30,
                "mapvideo": "0:1",
                "mapaudio": "0:0",
                "maxBitrate": 600000,
                "vcodec": "h264_omx",
                "packetSize": 1128,
                "audio": true

**Comment by tslamparter** [comment] 2020-05-26 00:45
Thanks @ciscosurplus . I got mine to work, but the quality is very bad and the audio chops. Any ideas? The stream looks fine in VLC on my mac so I assume it's the RPi. I increased its GPU memory to 512 and it didn't help.

**Comment by beele** [comment] 2020-05-26 06:12
The quality is limited by what ios requests the stream as (usually a very low res and low bitrate).
Since homebridge-camera-ffmpeg is also not working this is not an issue with this plugin and the problem lies with your ffmpeg settings/configuration parameters.

**Comment by VentingBow5** [comment] 2020-05-26 06:13
@beele I also tried your suggestion of installing Homebridge Camera FFmpeg but still get an exited code 1 from the plugin.

[5/26/2020, 08:12:10] [Camera-ffmpeg] Start streaming video from Achterdeur with 1280:720@15fps (299kBit)
[5/26/2020, 08:12:17] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

I will now try the settings as provided by @ciscosurplus.

**Comment by VentingBow5** [comment] 2020-05-26 06:18
@ciscosurplus I tried your settings but for me this does not work......

**Comment by beele** [comment] 2020-05-27 05:44
@VentingBow5 what is you host os? (version of os/node/homebridge/cpu-architecture)

**Comment by VentingBow5** [comment] 2020-05-27 09:43
I used the Official Homebridge Raspberry Pi Image. Hardware is Raspberry Pi 3B

OS: Raspbian GNU/Linux 10 (buster)
Node: v12.16.3
Homebridge version: Linux homebridge 4.19.97-v7+
CPU architecture: armv71

**Comment by miwagner1** [comment] 2020-05-28 22:15
This works for me with reduced delay.

```               
"vcodec": "copy",
"audio": true,
"maxStreams": 2,
"maxWidth": 1024,
"maxHeight": 576,
"maxFPS": 15,
"mapvideo": "0:1",
"mapaudio": "0:0",
"maxBitrate": 3000,
"packetSize": 376,
"videoFilter": "none",
"additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"```

**Comment by VentingBow5** [comment] 2020-05-29 05:28
This work for me as well @miwagner1 !! Thanks for this.

**Comment by beele** [comment] 2020-05-29 05:49
I'll be adding a wiki entry with different ffmpeg configs. I still don't quite understand why there is such a variety in ffmpeg configs that do/don't work with the same type of hardware.

@miwagner1 What camera's do you have?

**Comment by miwagner1** [comment] 2020-05-29 11:24
A g3 Flex and a g3 micro. Since the stream is already h264, the copy function uses minimal resources on a raspberry pi due to skipping the need to re encode. It also reduces the stream delay.

**Comment by a-rodriguez** [comment] 2020-05-29 11:52
@miwagner1 This worked for me also, thank you!
@beele Not sure if it helps, but I have UVC G3 and UVC G3 Flex. Just a suggestion, not sure if its possible, would be nice to edit mapvideo, mapaudio and videoFilter via the setting GUI if using Homebridge Config UI X. Thanks again for all the work on this.

**Comment by miwagner1** [comment] 2020-05-30 01:31
> I'll be adding a wiki entry with different ffmpeg configs. I still don't quite understand why there is such a variety in ffmpeg configs that do/don't work with the same type of hardware.
> 
> @miwagner1 What camera's do you have?

Ideally the “copy” config should be the preferred configuration due to performance and quality.

**Comment by tslamparter** [comment] 2020-05-30 21:25
@miwagner1 this helped mine stream a lot. The audio is still slightly choppy, but video is far superior. I have UVC-G3-BULLETs. Thanks!

@beele I also just migrated to a UDMP yesterday and had to go through the issue thread to figure out what needed to be changed in my config. Maybe a sample config for Unifi OS would be helpful as well. The only change was taking out the port number for the controller url (keep in the rtsp url).

**Closed** 2020-06-26 08:22 UTC

**Comment by sullyhome** [comment] 2020-06-30 23:25
No luck for me with those settings for G3 Bullet Cameras. (or G3 Flex)
